DATASET:
  DATASET: 'mix_smpl'
  SET_LIST:
    - ROOT: './data/h36m/'
      TEST_SET: 'Sample_20_test_Human36M_smpl'
      TRAIN_SET: 'Sample_5_train_Human36M_smpl_leaf_twist'
    - ROOT: './data/coco/'
      TRAIN_SET: 'train2017'
    - ROOT: './data/3dhp/'
      TRAIN_SET: 'train_v2'
  PROTOCOL: 2
  FLIP: True
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.3
  NUM_JOINTS_HALF_BODY: 8
  PROB_HALF_BODY: -1
  COLOR_FACTOR: 0.2
  OCCLUSION: True
MODEL:
  TYPE: 'HybrikTransformerSMPL24'
  PRETRAINED: ''
  TRY_LOAD: ''
  IMAGE_SIZE:
  - 256
  - 256
  HEATMAP_SIZE:
  - 64
  - 64
  NUM_JOINTS: 24
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 34
  EXTRA:
    SIGMA: 2
    BACKBONE: 'resnet'
    CROP: 'padding'
    AUGMENT: 'none'
    PRESET: 'simple_smpl_3d'
    DEPTH_DIM: 64
  POST:
    NORM_TYPE: 'softmax'
  TRANSFORMER:
    ARCH: 'custom'
    NUM_BLOCKS: 6
    NUM_LAYERS: 3
    NUM_HEADS: 8
    D_MODEL: 512
    LAYER_WIDTH: 512
    DROPOUT: 0.1
    RETAIN_ELEMENTS_LOW: 0.2
    RETAIN_ELEMENTS_HIGH: 1.0
LOSS:
  TYPE: 'L1LossDimSMPL'
  ELEMENTS:
    BETA_WEIGHT: 1
    BETA_REG_WEIGHT: 0
    PHI_REG_WEIGHT: 0.0001
    LEAF_REG_WEIGHT: 0
    TWIST_WEIGHT: 0.01
    THETA_WEIGHT: 0.01
    UVD24_WEIGHT: 1
    XYZ24_WEIGHT: 0
    XYZ_SMPL24_WEIGHT: 0
    XYZ_SMPL17_WEIGHT: 0
    VERTICE_WEIGHT: 0
TEST:
  HEATMAP2COORD: 'coord'
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 64
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  OPTIMIZER: 'adam'
  SCHEDULER:
    TYPE: 'InverseSquareRoot'
    WARMUP_UPDATES: 4000
    WARMUP_END_LR: 0.0005
  LR: 0.0005
  DPG_MILESTONE: 140
  DPG_STEP:
  - 160
  - 190
